# Generated by Django 3.1 on 2020-11-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('cloudeid', models.CharField(blank=True, db_column='cloudeId', max_length=100, null=True)),
                ('tenantid', models.CharField(blank=True, db_column='tenantId', max_length=100, null=True)),
                ('modelid', models.CharField(blank=True, db_column='modelId', max_length=100, null=True)),
                ('deviceid', models.CharField(blank=True, db_column='deviceId', max_length=100, null=True)),
                ('level', models.CharField(max_length=1)),
                ('type', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('rule', models.TextField()),
                ('createtime', models.DateTimeField(db_column='createTime')),
            ],
            options={
                'db_table': 'monit_event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MonitWorkcondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudeid', models.CharField(blank=True, db_column='cloudeId', max_length=100, null=True)),
                ('tenantid', models.CharField(blank=True, db_column='tenantId', max_length=100, null=True)),
                ('begintime', models.DateTimeField(db_column='beginTime')),
                ('endtime', models.DateTimeField(db_column='EndTime')),
                ('workingtime', models.DateTimeField(db_column='workingTime')),
                ('totalnum', models.IntegerField(db_column='totalNum')),
                ('createtime', models.DateTimeField(db_column='createTime')),
            ],
            options={
                'db_table': 'monit_workcondition',
                'managed': True,
            },
        ),
    ]
